# Generated by Django 2.1.2 on 2018-10-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181025_1102'),
        ('members', '0002_auto_20181024_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
